<div class="container-fluid h-100">
  <div class="row h-100">
    
    <div class="col-md-6 banner">
      <div class="row h-100 justify-content-center align-items-center">
        <div>
          <div class="communicationItem">
            <i class="fas fa-search fa-2x mr-3"></i>
            Explore o que te interessa.
          </div>
          <div class="communicationItem">
            <i class="fas fa-user-friends fa-2x mr-3"></i>
            Descubra o que as pessoas estão ecoando.
          </div>
          <div class="communicationItem">
            <i class="far fa-comment fa-2x mr-3"></i>
            Faça sua voz ecoar.
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
      <form >
        <div class="row">
          <div class="col">
            <input type="text" class="form-control" placeholder="E-mail">
          </div>
          <div class="col">
            <input type="password" class="form-control" placeholder="Senha">
          </div>
          <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-2 btn-entrar">Entrar</button>
          </div>
        </div>
      </form>

      <div class="row pt-5 pl-5 pr-5">
        <div class="col pl-5 pr-5 text-center">
          <img src="/img/echo_logo.png" alt="Logo ECHO" />
          <h1 class="title">Veja o que está ecoando no mundo agora</h1>

          <h2 class="mt-5 subtitle">Participe hoje do ECHO.</h2>
          <a href="/inscreverse" class="btn btn-primary btn-block mb-2 btn-inscrever">Inscrever-se</a>
        </div>  
      </div>
    </div>

  </div>
</div>